site_name: screenlamp
site_url: http://rasbt.github.io/screenlamp
site_author: Sebastian Raschka
site_description: A toolkit for ligand-based screening

repo_url: https://github.com/rasbt/screenlamp

#include_search: true # not necessary for this theme
docs_dir: sources
site_dir: html
theme: united

use_directory_urls: false
site_favicon: favicon.ico

markdown_extensions:
  - mathjax
  - extra
  - tables
  - fenced_code
extra_javascript:
  - https://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS_HTML
  - mathjaxhelper.js
extra_css:
  - extra.css

copyright: Copyright &copy; 2017 Michigan State University. Developed in the <a href="http://www.kuhnlab.bmb.msu.edu">PSA Lab</a>. <em>Sebastian Raschka et al. 2017</em>.

pages:
- Home: index.md
- Installation: installation.md
- Tools Overview: tools.md
#- Tutorial: tutorial.md
- Tutorial: workflow/example_1/example_1.md
- About:
  - Contact: contact.md
  - Release Notes: changelog.md
  - License: license.md
  - Citing screenlamp: cite.md
